on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    build:
      name: push docker image to docker hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: login to docker hub
          id: docker-hub
          env:
            username: ${{secrets.DOCKER_USERNAME}}
            password: ${{secrets.DOCKER_PASSWORD}}
          run: |
            docker login -u $username -p $password 

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and push
          uses: docker/build-push-action@v6
          with:
            platforms: linux/amd64,linux/arm64
            push: true
            tags: wackysysadmin/ocsp-responder:latest
          
        - name: push the docker image
          id: push-docker-image
          run: docker push wackysysadmin/ocsp-responder:latest
